---
title: "ST558 Project2 Blog"
author: "Chengxi Zou"
date: '2022-07-10'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, message = FALSE, warning = FALSE)
```

link to github page: https://github.com/ShanLLL52.github.io/ST558Project2

link to github repo: https://github.com/ShanLLL52/ST558Project2

# outlining the project

We are trying to predict the number of shares in social networks using predictive models among different data channels. The data set we have is the Online News Popularity Data Set, which summarizes a heterogeneous set of features about articles published by Mashable in two years.

We subset the data into each levels of article types before modeling. There exists six types in our data set.

As we want to investigate the effect of independent variables on the number of shares, the first step would be presenting a brief EDA to have a preliminary understanding of data, then modeling data with predictive models and compare them.

The predictive models we choose are linear regression model and ensemble tree-based models.

We use automating to present analysis results on different data sets.

I wrote the introduction, checked the subset data, did some numeric summaries, present some EDA results and fitted some models.

**what would you do differently?**

I would start earlier in order to better cooperate with my teammate.

**what was the most difficult part for you?**

The automating was difficult, we spent quit some time to figure it out.

**what are your big take-aways from this project?**

Github is really helpful for teamwork, and automating is amazing.

